const SONGS={
 twinkle:{title:'Twinkle Twinkle Little Star',diff:'★ EASY',notes:['C4','C4','G4','G4','A4','A4','G4','F4','F4','E4','E4','D4','D4','C4']},
 ode:{title:'Ode to Joy',diff:'★★ NORMAL',notes:['E4','E4','F4','G4','G4','F4','E4','D4','C4','C4','D4','E4','E4','D4','D4']},
 scale:{title:'C Major Scale',diff:'★ TRAINING',notes:['C4','D4','E4','F4','G4','A4','B4','C5']}
};
const NOTE_INDEX=['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
const noteToMidi=n=>{const m=n.match(/^([A-G]#?)(-?\d)$/);return m?(+m[2]+1)*12+NOTE_INDEX.indexOf(m[1]):null};
const midiToNote=m=>NOTE_INDEX[(m%12+12)%12]+(Math.floor(m/12)-1);
const midiToHz=m=>440*Math.pow(2,(m-69)/12); const hzToMidi=h=>Math.round(69+12*Math.log2(h/440)); const $=id=>document.getElementById(id);
const state={song:'twinkle',index:0,score:0,combo:0,maxCombo:0,attempts:0,hits:0,running:false,lastAccepted:0,stream:null,audio:null,raf:null};
const modeSelect=$('modeSelect'),inputSelect=$('inputSelect');
function buildSongCards(){const root=$('songCards');root.innerHTML='';Object.entries(SONGS).forEach(([id,s])=>{const b=document.createElement('button');b.type='button';b.className='song-card'+(id===state.song?' active':'');b.innerHTML=`<strong>${s.title}</strong><small>${s.diff}</small>`;b.addEventListener('click',()=>{state.song=id;buildSongCards();resetGame()});root.appendChild(b)})}
function rankFor(acc){return acc>=95?'S':acc>=88?'A':acc>=78?'B':acc>=65?'C':'D'}
function renderSong(){const s=SONGS[state.song];$('songTitle').textContent=s.title;$('difficulty').textContent=s.diff;$('noteTotal').textContent=s.notes.length;$('noteIndex').textContent=state.index;$('expectedNote').textContent=state.running&&state.index<s.notes.length?s.notes[state.index]:'—';$('expectedHz').textContent=state.running&&state.index<s.notes.length?`${midiToHz(noteToMidi(s.notes[state.index])).toFixed(1)} Hz`:'WAIT';$('progressBar').style.width=`${Math.min(100,state.index/s.notes.length*100)}%`;renderHighway()}
function renderHighway(){const notes=SONGS[state.song].notes,root=$('noteStream');root.innerHTML='';const center=state.index;for(let offset=-2;offset<=5;offset++){const i=center+offset;if(i<0||i>=notes.length)continue;const d=document.createElement('div');d.className='fall-note'+(i<center?' done':'')+(i===center&&state.running?' current':'');d.textContent=notes[i];d.style.top=`${30+(offset+2)*42}px`;root.appendChild(d)}}
function updateStats(){const acc=state.attempts?Math.round(state.hits/state.attempts*100):null;$('score').textContent=String(state.score).padStart(6,'0');$('combo').textContent=state.combo;$('accuracy').textContent=acc===null?'--%':`${acc}%`;const sc=acc===null?0:acc>=90?3:acc>=75?2:acc>=55?1:0;$('stars').textContent='★'.repeat(sc)+'☆'.repeat(3-sc);$('rankOrb').textContent=acc===null?'S':rankFor(acc)}
function setJudge(text,type=''){const e=$('judge');e.textContent=text;e.className='judge'+(type?' '+type:'');void e.offsetWidth;e.classList.add('pop');setTimeout(()=>e.classList.remove('pop'),300)}
async function startGame(){if(state.running)return;await countdown();state.index=0;state.score=0;state.combo=0;state.maxCombo=0;state.attempts=0;state.hits=0;state.running=true;state.lastAccepted=0;$('resultCard').hidden=true;setJudge('GO!');updateStats();renderSong();$('hint').textContent='STAGE START! 看目標音符，直接彈真鋼琴。'}
function countdown(){return new Promise(resolve=>{const el=$('countdown');el.hidden=false;let n=3;el.textContent=n;const t=setInterval(()=>{n--;if(n===0){el.textContent='GO!'}else if(n<0){clearInterval(t);el.hidden=true;resolve()}else el.textContent=n},650)})}
function resetGame(){state.running=false;state.index=0;state.score=0;state.combo=0;state.maxCombo=0;state.attempts=0;state.hits=0;updateStats();renderSong();setJudge('READY?');$('heardNote').textContent='—';$('heardHz').textContent='0 Hz'}
function finish(){state.running=false;const acc=state.attempts?Math.round(state.hits/state.attempts*100):0,stars=acc>=90?3:acc>=75?2:acc>=55?1:0,rank=rankFor(acc);$('resultRank').textContent=`RANK ${rank}`;$('resultStars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('resultText').textContent=`SCORE ${state.score} ｜ ACCURACY ${acc}% ｜ MAX COMBO ${state.maxCombo}`;$('resultCard').hidden=false;setJudge('CLEAR!','good');renderSong()}
function flashKey(note){document.querySelectorAll('.key,.black').forEach(k=>k.classList.toggle('active',k.dataset.note===note));setTimeout(()=>document.querySelectorAll(`[data-note="${note}"]`).forEach(k=>k.classList.remove('active')),180)}
function acceptNote(note,hz=0){$('heardNote').textContent=note;$('heardHz').textContent=hz?`${hz.toFixed(1)} Hz`:'SCREEN KEY';flashKey(note);if(!state.running||modeSelect.value==='free')return;const now=performance.now();if(now-state.lastAccepted<220)return;const expected=SONGS[state.song].notes[state.index];state.attempts++;if(note===expected){state.lastAccepted=now;state.hits++;state.combo++;state.maxCombo=Math.max(state.maxCombo,state.combo);const bonus=Math.min(250,state.combo*10);state.score+=100+bonus;state.index++;setJudge(state.combo>=8?'MARVELOUS!':state.combo>=4?'PERFECT!':'GREAT!','good');$('comboBurst').textContent=state.combo>=2?`${state.combo} COMBO!`:'';if(state.index>=SONGS[state.song].notes.length){updateStats();finish();return}}else{state.combo=0;state.score=Math.max(0,state.score-25);setJudge('MISS!','bad');$('comboBurst').textContent=`TRY ${expected}`;setTimeout(()=>$('comboBurst').textContent='',600)}updateStats();renderSong()}
$('startBtn').addEventListener('click',startGame);$('resetBtn').addEventListener('click',resetGame);$('againBtn').addEventListener('click',startGame);inputSelect.addEventListener('change',()=>{$('inputBadge').textContent=inputSelect.value==='mic'?'MIC MODE':'TOUCH MODE';$('hint').textContent=inputSelect.value==='mic'?'請啟動 MIC，再開始挑戰。':'可以直接點下方琴鍵測試街機流程。'});
function buildKeyboard(){const root=$('keyboard');let whitePos=0;for(let midi=48;midi<=72;midi++){const note=midiToNote(midi),black=note.includes('#');if(!black){const k=document.createElement('button');k.type='button';k.className='key';k.dataset.note=note;k.textContent=note;k.addEventListener('click',()=>acceptNote(note));root.appendChild(k);whitePos++}else{const k=document.createElement('button');k.type='button';k.className='black';k.dataset.note=note;k.textContent=note.replace(/\d/,'');k.style.left=`${whitePos*52-17}px`;k.addEventListener('click',()=>acceptNote(note));root.appendChild(k)}}}
async function startMicrophone(){try{if(state.stream)state.stream.getTracks().forEach(t=>t.stop());const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});state.stream=stream;const AC=window.AudioContext||window.webkitAudioContext,ctx=new AC();state.audio=ctx;await ctx.resume();const analyser=ctx.createAnalyser();analyser.fftSize=4096;analyser.smoothingTimeConstant=.12;ctx.createMediaStreamSource(stream).connect(analyser);const buf=new Float32Array(analyser.fftSize);$('audioStatus').textContent='🟢 MIC LIVE';$('micBtn').textContent='MIC LIVE';$('hint').textContent='麥克風已連線。把裝置放在鋼琴附近即可開始。';const loop=()=>{analyser.getFloatTimeDomainData(buf);let rms=0;for(const v of buf)rms+=v*v;rms=Math.sqrt(rms/buf.length);$('levelMeter').style.width=`${Math.min(100,rms*700)}%`;if(rms>.012){const hz=autoCorrelate(buf,ctx.sampleRate);if(hz>55&&hz<1800){const note=midiToNote(hzToMidi(hz));$('heardNote').textContent=note;$('heardHz').textContent=`${hz.toFixed(1)} Hz`;if(inputSelect.value==='mic')acceptNote(note,hz)}}state.raf=requestAnimationFrame(loop)};if(state.raf)cancelAnimationFrame(state.raf);loop()}catch(err){console.error(err);$('audioStatus').textContent='🔴 MIC ERROR';$('hint').textContent='無法取得麥克風權限。GitHub Pages 請使用 HTTPS 並允許麥克風。'}}
$('micBtn').addEventListener('click',startMicrophone);
function autoCorrelate(buffer,sampleRate){const size=buffer.length;let rms=0;for(let i=0;i<size;i++)rms+=buffer[i]*buffer[i];rms=Math.sqrt(rms/size);if(rms<.01)return-1;let r1=0,r2=size-1,th=.18;for(let i=0;i<size/2;i++){if(Math.abs(buffer[i])<th){r1=i;break}}for(let i=1;i<size/2;i++){if(Math.abs(buffer[size-i])<th){r2=size-i;break}}const b=buffer.slice(r1,r2),n=b.length,c=new Array(n).fill(0);for(let lag=0;lag<n;lag++){let sum=0;for(let i=0;i<n-lag;i++)sum+=b[i]*b[i+lag];c[lag]=sum}let d=0;while(d+1<n&&c[d]>c[d+1])d++;let max=-1,pos=-1;for(let i=d;i<n;i++){if(c[i]>max){max=c[i];pos=i}}if(pos<=0)return-1;let T0=pos;const x1=c[T0-1]||c[T0],x2=c[T0],x3=c[T0+1]||c[T0],a=(x1+x3-2*x2)/2,bv=(x3-x1)/2;if(a)T0-=bv/(2*a);return sampleRate/T0}
buildSongCards();buildKeyboard();renderSong();updateStats();
